services:
  db:
    image: mysql:8.0
    container_name: fashion_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - fashion_db_data:/var/lib/mysql
    networks:
      - fashion-network

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: employ_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      # 'db' (nombre del servicio) en la URL, no localhost
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${DB_NAME}?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    ports:
      - "8080:8080"
    networks:
      - fashion-network

networks:
  fashion-network:
    driver: bridge

volumes:
  fashion_db_data: